### ISSUE TITLE
Format of dataset 

### ISSUE THREAD

**Issue by getcontrol** [armaniv/ImageHistogram#1]
Hi thank you for this code its great!

Re: `PATH = '/media/vale/HDDVale/Uni/DataSet'  # the path where the dataset is located`

in file Histogram.py  ... should the MIDV-500 datasets be contained in my directory in the _50  original zips_ or unzipped into the _separate 50 folder directories_ ?

**Comment by armaniv** [comment]
The MIDV-500 dataset must be unzipped into the separate 50 folder directories.

**Comment by getcontrol** [comment]
Thanks, Histogram.py working now.
