### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by getcontrol** [armaniv/ImageHistogram#2]
When I run DocExtractor.py with relevant inputs , get error:

```
Traceback (most recent call last):
  File "DocExtractor.py", line 169, in <module>
    extract_document(sys.argv[1], sys.argv[2])
  File "DocExtractor.py", line 117, in extract_document
    kp_qr, des_qr, kp_tr, des_tr = compute_key_descriptor(img_query, path_img_query, img_train)
  File "DocExtractor.py", line 67, in compute_key_descriptor
    sift = cv.xfeatures2d.SIFT_create()  # Initiate SIFT detector
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'
```

These are my current versions:

Name: opencv-python
Version: 3.4.2.16
Location: /Users/getcontrol/ID_detection/.venv/lib/python3.7/site-packages
Requires: numpy
Required-by: 

Version: 3.4.2.16
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/skvark/opencv-python
Author: None
Author-email: None
License: MIT
Location: /Users/getcontrol/ID_detection/.venv/lib/python3.7/site-packages
Requires: numpy
Required-by: 

I think the issue is related to **AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'**
When I use latest  opencv-contrib-python-4.1.1.26 

Error =

`(-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration;`

Any workarounds?

**Comment by getcontrol** [comment]
Found the solution ,  need a version of opencv-contrib-pythonthat that still supports SIFT. 
i.e. the one you recommended!

```
pip3 uninstall opencv-python
pip3 install -U opencv-contrib-python==3.4.2.16
```

**Comment by jscul** [comment]
Don't think this solution works anymore.

```
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==3.4.2.16 (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58)
ERROR: No matching distribution found for opencv-contrib-python==3.4.2.16
```

**Comment by davidbp** [comment]
you can simply  install it without specifying the version: `pip3 install -U opencv-contrib-python` and it will work.

**Comment by MuhammadShifa** [comment]
The simple answer is here https://stackoverflow.com/a/70433685/14578749
