### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by getcontrol** [armaniv/ImageHistogram#3]
Can you provide an example of how to run DocExtractor.py ?

 For example - 

> 'query image' should be the model ?

Does this mean `path_to_the_query_img` should be precomp_key-des/model_30_ita.yml ?

Also, what does the print JSON dump after running Histogram.py do? Should it be saved in a -o output.json and then referenced? Unsure the relationship between histogram.py, .the .json, yml files, and how they relate to DocExtractor. Does DocExtractor extract anything from the identified ID doc, or just prove there's other similar documents in the dataset?

I'm very fascinated with this and would appreciate more usage examples, instructions etc!

**Comment by armaniv** [comment]
I think that the report linked in the README answers all your questions.
